### ISSUE TITLE
Update to R5?

### ISSUE THREAD

**Issue by godsyn** [HansAnderson/CommandSigns#3]
Any plans to update for R5?

```
Minecraft dev server launched.
174 recipes
27 achievements
15:35:44 [INFO] Starting minecraft server version 1.1
15:35:44 [INFO] Loading properties
15:35:44 [INFO] Starting Minecraft server on *:25569
15:35:45 [INFO] This server is running CraftBukkit version git-Bukkit-1.1-R4-13-g6381da2-b1952jnks (MC: 1.1) (Implementing API version 1.1-R5-SNAPSHOT)
15:35:45 [SEVERE] Could not load 'plugins/CommandSigns-1.2.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bukkit/event/player/PlayerListener
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:288)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:212)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:190)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:166)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:52)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:148)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.NoClassDefFoundError: org/bukkit/event/player/PlayerListener
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:787)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:447)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at com.hans.CommandSigns.CommandSigns.<init>(CommandSigns.java:28)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.player.PlayerListener
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 27 more
15:35:45 [INFO] Preparing level "world"
15:35:45 [INFO] Default game type: 0
15:35:45 [INFO] Preparing start region for level 0 (Seed: -97394964482756812)
15:35:45 [INFO] Preparing start region for level 1 (Seed: -97394964482756812)
15:35:46 [INFO] Preparing start region for level 2 (Seed: -97394964482756812)
15:35:46 [INFO] Preparing spawn area: 20%
15:35:46 [INFO] Server permissions file permissions.yml is empty, ignoring it
15:35:46 [INFO] Done (1.416s)! For help, type "help" or "?"
```

**Comment by HansAnderson** [comment]
Hey,

I don't think that I'll be working with plugins for a while. Feel free to
branch it if you want! It's a pretty basic plugin, and there's nothing
terribly fancy.

Hans

**Comment by AStevensTaylor** [comment]
Usable Jar
http://goo.gl/UmN8b

Source
http://goo.gl/F7jwK
